Add maven integration tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -92,3 +92,22 @@ jobs:
       - name: Check on failures
         if: steps.java11-maven-spring-fail.outcome != 'failure'
         run: exit 1
+  integrationtests-jdk-8-maven:
+    runs-on: ubuntu-18.04
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 8
+        uses: actions/setup-java@v3
+        with:
+          java-version: '8'
+          distribution: 'adopt'
+      - name: Run integration test - Java 8 + Spring + Maven + Should Succeed
+        run: cd ./integration-tests/java8-maven-spring-success && mvn clean install
+        id: java8-maven-spring-success
+      - name: Run integration test - Java 8 + Spring + Maven + Should Fail
+        run: cd ./integration-tests/java8-maven-spring-fail && mvn clean install
+        id: java8-maven-spring-fail
+        continue-on-error: true
+      - name: Check on failures
+        if: steps.java8-maven-spring-fail.outcome != 'failure'
+        run: exit 1
