Add integration tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,7 +16,7 @@ jobs:
           distribution: 'adopt'
       - name: Test with Gradle
         run: ./gradlew clean test -i
-  integrationtests:
+  integrationtests-jdk-11:
     runs-on: ubuntu-18.04
     steps:
       - uses: actions/checkout@v3
@@ -34,4 +34,23 @@ jobs:
         continue-on-error: true
       - name: Check on failures
         if: steps.java11-gradle-spring-fail.outcome != 'failure'
+        run: exit 1
+  integrationtests-jdk-17:
+    runs-on: ubuntu-18.04
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+      - name: Run integration test - Java 17 + Spring + Gradle + Should Succeed
+        run: cd ./integration-tests/java17-gradle-spring-success && ./gradlew clean test -i
+        id: java17-gradle-spring-success
+      - name: Run integration test - Java 17 + Spring + Gradle + Should Fail
+        run: cd ./integration-tests/java17-gradle-spring-fail && ./gradlew clean test -i
+        id: java17-gradle-spring-fail
+        continue-on-error: true
+      - name: Check on failures
+        if: steps.java17-gradle-spring-fail.outcome != 'failure'
         run: exit 1
