Add maven integration tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -2,7 +2,7 @@ name: CI
 on: [push]
 
 jobs:
-  build:
+  unittests:
     runs-on: ubuntu-18.04
     strategy:
       matrix:
@@ -110,4 +110,23 @@ jobs:
         continue-on-error: true
       - name: Check on failures
         if: steps.java8-maven-spring-fail.outcome != 'failure'
+        run: exit 1
+  integrationtests-jdk-17-maven:
+    runs-on: ubuntu-18.04
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+      - name: Run integration test - Java 17 + Spring + Maven + Should Succeed
+        run: cd ./integration-tests/java17-maven-spring-success && mvn clean install
+        id: java17-maven-spring-success
+      - name: Run integration test - Java 17 + Spring + Maven + Should Fail
+        run: cd ./integration-tests/java17-maven-spring-fail && mvn clean install
+        id: java17-maven-spring-fail
+        continue-on-error: true
+      - name: Check on failures
+        if: steps.java17-maven-spring-fail.outcome != 'failure'
         run: exit 1
