Add maven integration tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -73,3 +73,19 @@ jobs:
       - name: Check on failures
         if: steps.java8-gradle-spring-fail.outcome != 'failure'
         run: exit 1
+  integrationtests-jdk-11-maven:
+    runs-on: ubuntu-18.04
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'adopt'
+      - name: Run integration test - Java 11 + Spring + Maven + Should Fail
+        run: cd ./integration-tests/java11-maven-spring-fail && mvn clean install
+        id: java11-maven-spring-fail
+        continue-on-error: true
+      - name: Check on failures
+        if: steps.java11-maven-spring-fail.outcome != 'failure'
+        run: exit 1
